image: node:6
stages:
  - test
  - publish

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test

publish:
  stage: publish
  only:
    - /^v\d+\.\d+\.\d+$/
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
    - npm publish
